<?php
/**
 * CNTechnoLabs
 * Copyright (C) 2023 CNTechnoLabs 
 *
 * @category  CNTechnoLabs
 * @package   CNTechnoLabs_ScrollTop
 * @copyright Copyright (c) 2023 CNTechnoLabs
 * @license   http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author    CNTechnoLabs
 */

if ($block->getStatus()) { ?>
    <div id="scrolltop" title="<?php echo __('Back to Top'); ?>">
        <i class="arrowup"></i>
    </div>
<?php }; ?>
